//
//  ViewController.swift
//  RandomQuotes
//
//  Created by Devin Singh on 3/19/20.
//  Copyright © 2020 Devin Singh. All rights reserved.
//

import UIKit

class ViewController: UIViewController {
    
    
    var quotes = [
    "God will steer, but He won't row" ,
    "the easiest way to get rid of a minus is to turn into a plus" ,
    "with inconceivable ingenuity God is staging 'super colossal' entertainment for His children, making them actors as well as audience in His planetary theatre." ,
    "there are two ways of spreading Light; to be the candle or the mirror that reflects it" ,
    "what had once been dedicated to the soul was now dedicated to the sale" ,
    "meet the ego in the middle" ,
    "electricity - don't touch it" ,
    "blessed is Ha-Shem our God, the God of Israel, who dwells between the Cherubim" ,
    "I drank too much Universe and I blacked out" ,
    "Gilbert Keith Chesterton described paradox as 'truth standing on her head to attract attention'" ,
    "meekness compels God Himself" ,
    "humility is a realistic perspective of myself" ,
    "setting the alarm early and living life on Purpose shows Gratitude" ,
    "two men looked outside prison bars  one saw mud and another saw stars" ,
    "no manureno magic" ,
    "how am I <em>not</em> myself?" ,
    "I don't get to work on myself.  I am not my judge" ,
    "the people who are hardest to love are the ones who need it most" ,
    "sometimes you have to lose your mind before you come to your senses" ,
    "if you're not having fun you're missing the point!" ,
    "humility is the willingness to learn" ,
    "LISTEN BEFORE YOU BRING IT IN" ,
    "please Bless it or block it" ,
    "the flames of hell are but God's Love denied" ,
    "and yet Neo is unmistakable in what he says to Trinity: “If you could see them as I see them, they are all made of Light...” Indeed, the machines represent Spirit, but Spirit as alienated and therefore attacking..." ,
    "I hear and I forgetI see and I rememberI do and I understand" ,
    "there is no map to the human heart" ,
    "children are not vessels to be filledbut candles to be Lit" ,
    "show your scars" ,
    "be Kind, for everyone you meet is fighting a hard battle" ,
    "Frank's message was that the ego (or personality) needs to share stories, but that to invest energy into that level of reality was missing the point, which was “to be in the transcendent state in the midst of the illusion. And the way to maintain that was through breathing”" ,
    "one who desire's a rose must honor the thorn" ,
    "the whole Tao of Pooh, honestly" ,
    "when the spirit is right, details will take care of themselves" ,
    "scratched an itch I didn't know I had!" ,
    "everything that's new to me is an opportunity" ,
    "worked so well I stopped doing it" ,
    "you become what you practice" ,
    "you can only go as high as your foundation is solid and deep" ,
    "face your fear because the goal demands it. That is the warrior spirit" ,
    "God's first language is Silence. Everything else is a mistranslation" ,
    "the Game can't be won, only Played" ,
    "the more I think I need to be somewhere else, the less at easae I am with the here and now" ,
    "God is not attained by a process of addition to anything in the soul, but by a process of subtraction" ,
    "unrealistic expectations are premeditated resentments" ,
    "death leaves a heartache no one can healLove leaves a memory no one can steal" ,
    "'Faith has little to do with belief,' she answered. 'Faith is the courage to live your life as if everything that happens does so for your highest good and learning. Like it or not.'" ,
    "of myself I am nothingthe Father doeth the works" ,
    "I don't get drunk over the facts, I get drunk over the feelings" ,
    "surrender to the resistance" ,
    "observers of the tao do not seek fulfillmentnot seeking fulfillment, they are not swayed by a desire for change" ,
    "I am the windowGod is the Lightthe ego is the shutter" ,
    "what I'm for  I'm looking WITH" ,
    "God has a tremendous sense of humor. That's why he hid himself in the last place we'd ever look" ,
    "Love is patient" ,
    "don't try to make things happen, let things happen" ,
    "you are always a slave to what you're not aware of" ,
    "sometimes I HAVE to believe that Heaven is just a new pair of glasses" ,
    "the view out is never clear, the view in is never foggy" ,
    "I have learned from Him, to see without eyes, to hear without ears, to drink without mouth" ,
    "to stop without knowing how one stops -- this is tao" ,
    "God comes to the hungry in the form of food" ,
    "when I don't who I am, I serve youwhen I know who I am, I AM you" ,
    "if you don't have any principles to live by, then ultimately you don't have any reason to live" ,
    "since meaning is a human invention, let's make it a positive experience!" ,
    "I don't think God's obligated to touch you if you would rather sit in shit than work a shovel" ,
    "do not interfere with other people's connection to Heaven" ,
    "does every death remind us of our own?" ,
    "difficulties are the practice" ,
    "anonymity is a way for me to work on my humility" ,
    "generosity is giving more than you canpride is taking less than you need",
    "don't take the mind so personally XD" ,
    "better to stand on the firmness of emptiness than the quicksand of somethingness" ,
    "see no evilhear no evilspeak no evil" ,
    "Heaven is covered with constellations, Earth with waterways, and man with channels" ,
    "food is either medicine or poison" ,
    "there is no way to peace;Peace is the Waythere is no way to happiness;Happiness is the Waythere is no way to love;Love is the Way" ,
    "there are no maps; no more creeds or philosophiesfrom here on in, the directions come straight from the Universe" ,
    "the answer lies within" ,
    "keep it sacred" ,
    "find your center" ,
    "We are always practicing something" ,
    "the effect you have on people is the only thing that matters" ,
    "the spiritual path is really about surrendering to that which is greater than us" ,
    "there is no greater obstacle to God than time" ,
    "what you think, you become" ,
    "what is one way you experience being present?" ,
    "seek no external refuge" ,
    "happiness comes when what you say, think and do are in harmony" ,
    "the answer lies within" ,
    "this too shall pass" ,
    "there for the grace of God go we" ,
    "Marry your soul, for that wedding is the Way" ,
    "wherever you go, there you are" ,
    "the goal isn’t to get high, it’s to get liberated" ,
    "To travel well is better than to arrive" ,
    "kill time" ,
    "Silence can wound as surely as the twisting lash" ,
    "if you envy someone for all the right reasons then you are halfway to wisdom" ,
    "forgiveness is the key to Heaven" ,
    "treat everyone you meet like God in drag" ,
    "the eyes are fate's mirror" ,
    "Zen is simply that state of centeredness which is here and now" ,
    "those who know do not say" ,
    "yield and overcome" ,
    "dropping in this strange designnone is yours and far less is mine" ,
    "in Being, subject and object disappear" ,
    "everything in this world is magic, except the magician" ,
    "watch the seeker" ,
    "the sea refuses no river" ,
    "the idea is to remain in a state of constant departure, while always arriving" ,
    "dream is destiny" ,
    "action > thought" ,
    "FOCUS" ,
    "there are no ordinary moments!" ,
    "life develops what it demands" ,
    "we can master suffering by letting go of desire!" ,
    "camouflage yourself" ,
    "the way to control your emotions is to let them flow, and then let them go" ,
    "the organs weep the tears that the eyes refuse to shed" ,
    "happiness isn’t something we getit’s something we give" ,
    "I don’t believe in miracles. I rely on them" ,
    "you practice gymnastics, I practice everything" ,
    "use intuition and analysis, but not at the same time" ,
    "in combat and in life, if you start thinking too much, you’re dead" ,
    "you don’t have to know everything about the ocean to swim in it" ,
    "don’t mistake the wrapping paper for the gift" ,
    "to the fish, the sea is air!" ,
    "among friends, there are no goodbyes" ,
    "everything is a dream within a dream" ,
    "it doesn’t matter where you’re going, as long as you are on your way" ,
    "Truth without Love is Crueltyconfrontation without Solution is brutality" ,
    "the less I define my HP, the more it is capable of" ,
    "all energy flows to the whim of the Great Magnet" ,
    "know the difference between intuition and insanity" ,
    "serenity is the passport to the Presence of God" ,
    "forgive him" ,
    "forgive her" ,
    "what you see at any time is nothing but your own concept" ,
    "'In consequence of the great Law of Life, of which the whole Sermon on the Mount is an exposition, we can get only what belongs to us at any time, and nobody can prevent our getting that' and so all persecution and hindrance are absolutely from within" ,
    "all of humanity’s problems stem from man’s inability to sit quietly in a room alone" ,
    "what you are shouts so loudly that I cannot hear what you are saying" ,
    "it speaks for itself, but in utter silence, and does much of its best work unconsciously. Its mere presence heals and blesses all aroud it without special effort" ,
    "Never try to force other people to accept Spiritual Truth" ,
    "feed peopleserve people" ,
    "everything is a dream" ,
    "I will not should myself today" ,
    "before you can see the Light, you have to deal with the darkness" ,
    "you can only do one thing at a time" ,
    "comparison as a form of suffering" ,
    "here and now, breathe and relax" ,
    "what is the good life to you?" ,
    "daily life is a form of spiritual weight training" ,
    "Ships are safe in harborbut that’s not what ships are for" ,
    "Imagination" ,
    "Lose judgment and don’t let the senses lead you" ,
    "Can you see silence?" ,
    "You ain’t gonna learn what you don’t wanna know" ,
    "Do it well or not at all!" ,
    "learn to deal with the valleys, the hills will take care of themselves" ,
    "my program vs THE program" ,
    "not all questions need answers!" ,
    "turn to face the sun and the shadows will fall behind you" ,
    "a giving person will constantly be on the receiving end" ,
    "path of consideration" ,
    "the less I think, the better" ,
    "happiness is reality minus expectations" ,
    "no preference!" ,
    "vegetable or animalFlora or Fauna?" ,
    "the cord of breath ties the soul to the body" ,
    "this being is also the very fabric and blueprint of consciousness—the Tree of Life, itself" ,
    "if you want peace of mind, I suggest that you resign as the general manager of the universe" ,
    "the program is a soft comfy pillow for those who can’t sleep, and a bucket of ice water for those who’ve been sleeping too long" ,
    "“We’re all self-centered, Dan — the question is, which ‘self’ are you centered on — the Basic Self, Conscious Self, or Higher Self?”" ,
    "SERVICE1 - self service2- service with strings attached3 - service out of duty and responsibility4 - TRUE service out of heart awareness" ,
    "Honor your process. Compassionate self-awareness leads to change; harsh self-criticism only holds the patterns in place, creating a stubborn and defensive Basic Self. Be gentle with yourself as you would with a child. Be gentle but firm. Give yourself the space to grow. But remember that the timing is in God’s hands, not yours" ,
    "Remember, friend, as you pass by,As you are now, so once was I.As I am now, so you must be.Prepare yourself to follow me.”" ,
    "Basic self - belly, body, childlike, vitality, funConscious self - head, mind, calculating, problem solving, analyticalHigher self - above head, inspiration, guidance, purpose" ,
    "Have them work in harmony" ,
    "Our prayers are always answered, sometimes God says noWhy do parents say no to their children?" ,
    "Discomfort is one way are basic self gets our attention" ,
    "you’re searching for your path even as you walk upon it" ,
    "trust in God, but tie your camel" ,
    "Pray as if everything depended on GodWork as if everything depended on man" ,
    "Shape shifting is a form of deep empathy, you feel your way into bird awareness" ,
    "Earth is A divine school and daily life is our classroom" ,
    "once you get across the river, forget the boat" ,
    "what is to give light is to endure burning" ,
    "Journal of Spirit / Inner Records" ,
    "unexpressed emotion is stored in the muscles of the body" ,
    "everything is difficult until it becomes easy" ,
    "we’re not here to get rid of the ego, we are here to transcend it. And that’s a big difference" ,
    "The advanced yogi, withholding all his mind, will, and feeling from false identification with bodily desires, uniting his mind with superconscious forces in the spinal shrines, thus lives in this world as God hath planned, not impelled by impulses from the past nor by new witlessnesses of fresh human motivations. Such a yogi receives fulfillment of his Supreme Desire, safe in the final haven of inexhaustibly blissful Spirit" ,
    "grow from the bottom upDon’t attempt to drag Heaven down" ,
    "the Truth is also seeking the seeker" ,
    "Zen BuddhismDon’t even think about it" ,
    "is material in service of Spirit?or is it the other way around?" ,
    "the kingdom of God is not for those who cannot relinquish worldly desires" ,
    "LOVE>FEAR" ,
    "Out of self, more God" ,
    "less judgement more tolerance" ,
    "we can’t self will our spiritual development" ,
    "Alcoholism is a prison where the key lies inside" ,
    "On really romantic evenings with myself, I go salsa dancing with my confusion" ,
    "A single ego is a disturbingly narrrow way to view this entire universe" ,
    "It’s always our decision, who we are" ,
    "Which is the most universal human characteristic? Fear? Or laziness?" ,
    "Lord I pray not for a lighter load,But for stronger shoulders" ,
    "Through failure, successI'll understand when you done your best, I am the Lord, thy God, and I'll be with thee" ,
    "make sure your head is connected to your heart!" ,
    "find your Muse" ,
    "clarity of thought is not equal to Truth" ,
    "I’ve had many troubles in my life, most of which never happened!" ,
    "Contend with our experience, rather than all the philosophical descriptions of our experience" ,
    "then I went home, thinking about my mind. A self defeating activity if ever there was one" ,
    "I can walk the long way if that’s what you want" ,
    "the brain is real. The mind is not" ,
    "the less I define my HP, the more it is capable of" ,
    "all energy flows to the whim of the Great Magnet" ,
    "know the difference between intuition and insanity" ,
    "'All idealism, the religious systems of all cultures, sees creation in terms of a descending series of emanations from the cosmic mind. But what is distinctly esoteric is this identifying of these emanations with the spirits of the stars and planets on the one hand and occult physiology on the other. It is this that leads to astrology, alchemy, magic and practical techniques for achieving altered states'" ,
    "Six blind men and the elephant" ,
    "The truth will make you free, but first it will make you uncomfortable" ,
    "Not one single atom opposes you" ,
    "Enlightenment is an accidentPractice makes you accident prone" ,
    "Can you find your mind?" ,
    "I want to be a spearhead of Gods ever developing universe!" ,
    "Proper posture is a way of blending with gravityProper attitude is a way of blending with life!" ,
    "'Following Plato they believed that all learning is a process of remembering. Our minds are protrusions of the great central cosmic mind into the material world. Everything that has been experienced or thought in history is held in the memory banks of the cosmic mind - or perhaps, more accurately, lives in a sort of eternal now'" ,
    "“The Commedia shows how when we behave badly in this life we are already constructing a Purgatory, a Hell, for ourselves in another dimension that intersects with our everyday lives. We are already suffering, tormented by demons. If we do not aspire to move up the spiral of the heavenly hierarchies, if we ‘make do’ with purely earthly successes and pleasures, we are already in Purgatory”" ,
    "“Free will does not mean that you establish the curriculum;only that you can elect what you want to take at a given time”" ,
    "Do not turn the mind into an enemy, for you will be fighting against yourself. Instead, turn into a tool which serves you and God" ,
    "“All idealism, the religious systems of all cultures, sees creation in terms of a descending series of emanations from the cosmic mind. But what is distinctly esoteric is this identifying of these emanations with the spirits of the stars and planets on the one hand and occult physiology on the other. It is this that leads to astrology, alchemy, magic and practical techniques for achieving altered states" ,
    "the truth will make you free, but first it will make you uncomfortable" ,
    "not one single atom opposes you" ,
    "Enlightenment is an accident.Practice makes you accident prone" ,
    "Can you find your mind?" ,
    "Resist nothing" ,
    "What am I?" ,
    "Know the difference between intuition and insanity" ,
    "REFRAIN FROM GIVING UNWARRANTED ADVICE" ,
    "Pride —> HumilityGreed —> CharitySloth —> DiligenceEnvy —> GratitudeWrath --> PeaceLust --> LoveGluttony --> Balance" ,
    "Return good for evil, forget your own suffering for another’s, and Renounce the fruit of your works - let your work be its own reward" ,
    "If you fight your death, you’ll feel the demons tearing away at your life, but if you have the right attitude to death, you will be able to see that the devils are really angels setting your spirit free" ,
    "He who fears death is already dead" ,
    "I’ve lost my mind and can’t seem to find it anywhere!" ,
    "when thoughts touch the present, they dissolve" ,
    "leave behind the self serving reverie" ,
    "Right and wrong will break your brain. Think in terms of “will this help or will this hurt”" ,
    "Life is not suffering, it’s just that you will suffer it until you can let go of mind attachments and just go for the ride freely no matter what happens" ,
    "Wisdom doesn’t come from ego" ,
    "from now on ordinary knowledge will no longer satisfy you in afraid" ,
    "when I asked “what is that?”I heard “It wouldn’t make sense in English”" ,
    "Be impeccable with your word. Don't take anything personally. Don't make assumptions Always do your best" ,
    "all talking is lying" ,
    "the first to speak is the first to lie" ,
    "the secret to living well and longer is: Eat half, walk double, laugh triple, and love without measure" ,
    "If you removed the sympathetic nervous system from the body and stood it up on its own, it would look like a tree. As one of Britain’s leading homeopathic healers put it to me, in a rather beautiful phrase: The sympathetic nervous system is the gift of the vegetable kingdom ”" ,
    "Memory has to be strong enough to enable us to act without forgetting what we wanted to do, to learn without ceasing to be the same person, but it also has to be weak enough to allow us to keep moving into the future." ,
    "The how, the Tao of intent and motive, that is the key" ,
    "We missed the reality and beauty of the forest because we were diverted by the ugliness of some of its trees" ,
    "Wealth is the ability to fully experience life" ,
    "If God is omnipotent, and She actually has a vested interest in each and everyone of our individual wellbeings and deepest aspirations, then there is real Power at work there. A Power that needs to be respected." ,
    "Philippians 2:12-13, Paul writes, “Therefore, my dear friends, as you have always obeyed – not only in my presence, but now much more in my absence – continue to work out your salvation with *fear and trembling, for it is God who works in you to will and to act according to His purpose.*" ,
    "My definition of a devil is a god who has not been recognized. That is to say, it is a power in you which you have not given expression, and you push it back. And then, like all repressed energy, it builds up and exiles the position you were trying to create" ,
    "Luck is what happens when fate gets tired of waiting" ,
    "The only kingdom that makes any man a king is the kingdom of his soul" ,
    "Whatever you do in life, do it with courage and you won't go far wrong" ,
    "Practice surrender by refraining from labeling the now" ,
    "In moments of charity there is no giver and no receiver. Only a shared moment of being" ,
    "When you accept what is, every piece of meat is the best. Everything is as is should be. That is enlightenment" ,
    "Somebody once told me the definition of hell: “On your last day on earth, the person you became will meet the person you could have become.”" ,
    "I prefer to be a dreamer among the humblest, with visions to be realized, than lord among those without dreams and desires" ,
    "To be closer to GodBe closer to people" ,
    "Fate gives us all three Teachers, three Friends, three enemies, and three great loves in our lives.We can never know which is which until we've loved them left them or fought them" ,
    "Love goes on forever because love was born in the part of us that does not die" ,
    "You can create the space for transformation to occur, but you can't transform anything yourself" ,
    "If the mind is not overlaid with wind and waves, you will always Be living among blue mountains and green trees. If your true nature has the creative force of Nature itself, wherever you may go, you will see the fishes leaping and geese flying" ,
    "Only when you have no thing in your mind and no mind in things are you vacant and spiritual, empty and marvelous" ,
    "The conflict between right and wrongIs the sickness of the mind" ,
    "Outside teaching; apart from traditionNot founded on words and lettersPointing directly at the human mind" ,
    "The Tao belongs neither to knowing nor not knowing. Knowing is false understanding; not knowing is blind ignorance. If you really understand the Tao beyond a doubt, it's like the empty sky. Why drag in right and wrong?" ,
    "To be awakened at all is to be awakened completely, for, having no parts or divisions, the Buddha nature is not realized bit by bit" ,
    "If, in questioning you, someone asks about being, answer with nonbeing. If he asks about nonbeing, answer with being. If he asks about the ordinary man, answer in terms of the sage. If he asks about the sage, answer in terms of the ordinary man. By this method of opposites mutually related there arises an understanding of the Middle Way. For every question that you are asked, respond in terms of its opposite" ,
    "Don't cling. Don't seek" ,
    "Seeking for Buddha nature is much like riding an ox in search of the ox" ,
    "When the fish is caught, the trap is forgotten" ,
    "Tathata therefore indicates The world just as it is, unscreened and undivided by the symbols and definitions of thought" ,
    "If you abandon all restraint, carry your wishes to their furthest limits, open your heart boundlessly, there is not a single moment when you will not find all you could possibly desire. The present moment holds infinite riches beyond your wildest dreams" ,
    "They who know God most perfectly perceive most clearly that He is perfectly incomprehensible" ,
    "Reverse the arrow of attention, and enter the realm of Certainity" ,
    "There's no longer any need to believe when one SEES the Truth" ,
    "The foolish reject what they see, not what they think. The wise reject what they think, not what they see...Observe things as they are and don't pay attention to other people" ,
    "To one who knows nothing, it is clearly revealed" ,
    "When thine eye is singleThy whole body also is full of light" ,
    "No one who puts his hand to the plow and looks back, is fit for the kingdom of God" ,
    "God is a metaphor for that which transcends all levels of intellectual thought. It’s as simple as that" ,
    "It is no merely human joy to lose oneself like this, so to be emptied of oneself as though one almost ceased to be at all; it is the bliss of heaven... how otherwise could God be 'all in all', if anything of man remained in man" ,
    "the basic myth of Hinduism is that the world is God playing hide and seek with himself" ,
    "What we call ‘me’ is the thing between the in breath and the out breath" ,
    "Your life situation is a result of timeYour life is now" ,
    "If not now, when?" ,
    "End the delusion of time" ,
    "Time and mind are inseparable" ,
    "Remove time from the mind and it stopsUnless you choose to use it" ,
    "To identify with your mind is to be trapped in time" ,
    "A compulsion to live exclusive through memory and anticipation creates an endless preoccupation with the past and future" ,
    "The Force that can be forced is not the eternal Force" ,
    "An emotion is where the mind meets the body" ,
    "Espiritum vinci espiritus(Higher Power overcomes alcoholism)" ,
    "The map is not the territory" ,
    "The finger pointing at the moon is not the moon" ,
    "Analyzing the pointer is pointless" ,
    "Do you have a little room where you can close the door and be alone?That is your cave. That is your sacred mountain. That is where you will find the kingdom of God" ,
    "What one does not trouble to find within will not be discovered by transporting the body hither and yon. As soon as the devotee is WILLING to go even to the ends of the earth for spiritual enlightenment, his guru appears nearby" ,
    "One who is immortal and who has control of everything that happens to him strikes me as self condemned to eternal boredom, since he lives in a world without mystery or surprise." ,
    "Explain Heaven in terms of the Earth" ,
    "Humility is knowing that I am a very small fiber in a brilliant cosmic tapestry, and the Weaver knows exactly where I fit." ,
    "I had to sink to great moral depths, to thoughts of suicide, to experience Grace" ,
    "Today he saw only one of the river’s secrets, one that gripped his soul. He saw that the water continually flowed and flowed and yet it was always there; it was always the same and yet every moment it was new" ,
    "Above all, he learned from it (the river) how to listen, to listen with a still heart, with a waiting open soul, without passion, without desire, without judgement without opinions" ,
    "Wisdom is not communicable" ,
    "Knowledge can be communicated, but not wisdom" ,
    "Time is not real. I have realized this repeatedly. And if time is not real, then the dividing line that seems to be between this world and eternity, between suffering and bliss, between good and evil, is also an illusion" ,
    "The spiritual path is really about surrendering to that which is greater than us" ,
    "Breathing in, I calm body and mind. Breathing out, I smile. Dwelling in the present moment I know this is the only moment." ,
    "All that is necessary to awaken to yourself as the radiant emptiness of spirit is to stop seeking something more or better or different, and to turn your attention inward to the awake silence that you are." ,
    "When meditation is mastered, the mind is unwavering, like the flame of a lamp in a windless place" ,
    "‎The mental suffering you create is always some form of non-acceptance, some form of unconscious resistance to what is. On the level of thought, the resistance is some form of judgement. The intensity of the suffering depends on the degree of resistance to the present moment" ,
    "If your mind is empty, it is always ready for anything; it is open to everything. In the beginner’s mind there are many possibilities, in the expert’s mind there are few" ,
    "To be free from bondage the wise person must practise discrimination between One-Self and the ego-self. By that alone you will become full of joy, recognising Self as Pure Being, Consciousness and Bliss." ,
    "The ultimate meditation is: surrender to reality. The more you fight, the more you are in conflict with it, the more you will be a loser. In deep surrender, the ego disappears. And when the ego is not there, for the first time you become aware of that which has always been there." ,
    "Learn to live without self concern. For this you must know your own true being as indomitable, fearless and ever victorious. Once you know with absolute certainty that nothing can trouble you but your own imagination, you come to disregard your desires and fears, concepts and ideas, and live by truth alone." ,
    "Integrated meditation practice is like a healthy diet which is indispensable for maintaining your vitality and resistance to disease. Likewise, a balanced meditative practice in the course of a socially engaged way of life heightens your psychological immune system, so that you are less vulnerable to mental imbalances of all kinds." ,
    "When one past thought has ceased and a future thought has not yet risen, in that gap, in between, isn’t there a consciousness of the present moment; fresh, virgin, unaltered by even a hair’s breadth of a concept, a luminous, naked awareness? Well, that’s what naturally peaceful awareness is." ,
    "The ultimate way of Being lies beyond all contradictory pairs of opposites with which our two dimensional thinking mind operates. As soon as we are successful in silencing the restless activity of the thinking mind and give a chance to intuition, the pure all embracing spirit in us will manifest effortlessly." ,
    "If your mind is happy then you are happy anywhere you go. When wisdom awakens within you, you will see Truth wherever you look. Truth is all there is. It’s like when you learned how to read, you can then read anywhere you go." ,
    "Flow with whatever is happening and let your mind be free. Stay centered by accepting whatever you are doing. This is the ultimate." ,
    "To meditate means to realize inwardly the imperturbability of the Essence of Mind. The reason why we are perturbed is because we allow ourselves to be carried away by the circumstances we are in. Those who are able to keep their mind unperturbed, irrespective of circumstances, have attained Inner Peace." ,
    "If you are unable to find the truth right where you are, where else do you expect to find it?" ,
    "We live in illusion and the appearance of things. There is a reality. We are that reality. When you understand this, you see that you are nothing, and being nothing, you are everything. That is all." ,
    "This is the real secret of life ~ to be completely engaged with what you are doing in the here and now. And instead of calling it work, realize it is play." ,
    "Life is this simple:we are living in a world that is absolutely transparent and the divine is shining through it all the time. This is not just a nice story or a fable, it is true." ,
    "If you are willing to experience anything directly and immediately, whether good or bad, joyous or hateful, you will recognize that what you are running from does not exist, and what you are running toward is already here." ,
    "Meditation is for you to realise that the deepest nature of your existence is beyond thoughts and emotions, that it is incredibly vast and interconnected with all other beings." ,
    "Many years ago, their was a young meditator who had heard of an old hermit who lived alone on an island that possessed remarkable spiritual powers. Upon his arrival to the island, he eventually found his way to the old man to ask for a morsel of wisdom. The old man told him he repeats but one simple mantra and the meditator was delighted to learn that it was the very same mantra that he was practicing. However, when the old man recited it, the young meditator was horrified and informed him that his life was wasted, for he had it all wrong. The old man thanked him and asked to be left alone so he could set about correcting his mistake immediately. On his way back across the lake, the meditator thoughtfully reflected on how fortunate the old hermit was to have been corrected, when suddenly he heard someone ask 'Excuse me, I hate to bother you, but I've forgotten the mantra. Would you mind repeating it for me once more?' The young meditator immediately turned his head and was absolutely astonished when he found himself face to face with the old hermit. The meditator was amazed as he struggled to mouth the correct mantra. The old man thanked him and began to carefully repeat the correct mantra as he slowly walked across the surface of the water back to the island." ,
    "You only find God when you realize you don't need to seek God" ,
    "Never thought I'd live to see the dayWhere everybody's words got in the way" ,
    "Words: They always become a little different immediately they are expressed, a little distorted, a little foolish" ,
    "Gain more energy, waste less energy, spend the energy so next time you’ll need less to achieve more. Increase human mass, reduce retarding force, and increase the force accelerating the human mass. Follow this process with reason." ,
    "Many men spend their whole lives fishing without realizing that it is not a fish they were after." ,
    "Poetry often enters through the window of irrelevance" ,
    "A wise man once said nothing" ,
    "Gaining facility and knowledge of Zen, expression of Zen, or presence of awareness, is not Zen" ,
    "First ecstasy, then the laundry" ,
    "Action cures fear" ,
    "Mind cannot seek mind successfully" ,
    "A flower does not have to compete with the flower next to it, it just blooms" ,
    "Follow your bliss and the universe will open doors for you where there were only walls" ,
    "There are no facts, only interpretations" ,
    "No one can teach you anything. You can only help a man find what he seeks in himself." ,
    "What’s the sound of one hand clapping?" ,
    "What you are looking for, is what is looking" ,
    "The Kundalini is the Serpent Power of the Mother aspect coiled up in the Muladhar chakra situated at the base of the spine in each person. In a spiritually advanced individual the awakened Kundalini energy rises up along the spinal column piercing the chakras and conferring new powers and states of consciousness as it rises until full Samadhi is attained on its reaching the highest chakra at the crown of the head." ,
    "It (the state of mind) should be like a lotus leaf, which though in water, with its stem in the mud and flower above, is yet untouched by both. Similarly, the mind should be kept untainted by the mud of desires and the water of distractions, even though engaged in worldly activities." ,
    "The Ocean has plenty of water. It is the size of the container brought to collect it that determines the quantity taken" ,
    "What's left in our heart is all we have" ,
    "When love and hate disappearEverything is left, undisguised" ,
    "When you accept yourself the whole world accepts you" ,
    "Learn form and basics before breaking tradition and making it your own practice" ,
    "it is presented right to your face, and at this moment the whole thing is handed over to you… Look into your whole being… Let your body and mind be turned into an inanimate object of nature like a stone or a piece of wood; when a state of perfect motionlessness and unawareness is obtained all signs of life will depart and also every trace of limitation will vanish" ,
    "There is a tremendous freedom and oneness with all things, a miraculous transcendent experience that is awakened within us when united with the eternal now.  However, we can be robbed of an even more grand experience if we are not careful to be conscious of when we are actually avoiding the now.  To 'get over it,' is to ignore the now, to turn a blind eye to a great treasure of life and equivalent to throwing out the prima materia.  The lead which is the gold. Try rather again and again' , leaning into the discomfort and embracing it as if you had called upon it.  For it is through this embrace that comes a deeper discovery and marriage with the gem of all gems.  That which cannot be broken, that which is eternal, the immortal medicine." ,
    "Be turned to me with all your heart and do not cast me aside because I am black and swarthy, because the sun hath changed my colour and the waters have covered my face and the land hath been polluted and defiled in my works; for there was darkness over it, because I stick fast in the mire of the deep and my substance is not disclosed.  Wherefore out of the depths have I cried, and from the abyss of the earth with my voice to all you that pass by the way.  Attend and see me, if any shall find one like unto me, I will give into his hand the morning star." ,
    "The universe is an infinite sphere whose center is everywhereand whose circumference is nowhere" ,
    "The head doesn’t get to take the spiritual journey, only the Heart does" ,
    "Be Still" ,
    "The point isn’t to get away from the shit, the point is to find the shit you’re comfortable dealing with" ,
    "forget about it" ,
    "backwards law" ,
    "sit like a turtlewalk like a pigeonsleep like a dog" ,
    "a slip of a lip can sink a ship" ,
    "turn the Light around" ,
    "You want answers? Stop asking questions and follow Me" ,
    "I have a harder time being right than being wrong right now" ,
    "Control is an illusion" ,
    "fight the current or ride the wave" ,
    "Politeness is the flower of humanity" ,
    "Earth laughs in flowers" ,
    "Flowers don't tell, they show" ,
    "Flowers are the music of the ground" ,
    "And so Jesus says that if, when we are about to pray, or remember that we have any wrong thoughts or hard feelings about our brother man, no matter who he may be, and irrespective of whether the object of our hostile thought be an individual or a body of people, we must pause there and treat ourselves until we have got rid of this sense of hostility, and have once more restored the seamless garment of our spiritual integrity" ,
    "journey inwards" ,
    "how's your soul?" ,
    "God cannot fill a heart and mind which is already full" ,
    "follow one single thought to its conclusion don't jump from branch to branch in the monkey-mind metaphor, but follow any single thought to its endwhen you do this, you arrive at real silence even if just for a moment" ,
    "we are speeding past the very things we think we are seekingbut with realizationn comes the experience of wonder and delight for the most mundane and ordinary occurences that we so easily take for granted" ,
    "in an age of distration, nothing can feel more luxurious than paying attention" ,
    "Trappist monks would only speak to move along necessary everyday activites" ,
    "70%" ,
    "...that sort of fire... which must take hold of people in some way - give them either pleasant or unpleasant sensationthe poem means to remind it's readers that they are alive; the author himself wishes for no higher effect" ,
    "the only way to be happy is to loveunless you love, you're life will flash by" ,
    "the loss of innocence is not a singular event in history but rather an axiom of human experience, repeated in every generation and in the consciousness of every individual" ,
    "be open to the experience of being wrong" ,
    "it's not what we do, it's how we do it" ,
    "we are all just walking each other home" ,
    "when you know how to listen, everybody is the guru" ,
    "it's impossible for a man to learn what he thinks he already knows" ,
    "How can I help?" ,
    "A lot of times people look at the negative side of what they feel they can't do. I always look on the positive side of what I can do " ,
    "My Soul has no price" ,
    "Analysis can become paralysis" ,
    "Don't speak unless you're spoken to" ,
    "us humans often look out the window instead of at our reflection because it sits better with our psyche" ,
    "For me, fear is sometimes the realization that I am gripping the steering wheel too hard - and I'm not even supposed to be in the driver's seat" ,
    "The solution to one problem is merely creation of the next" ,
    ]


    override func viewDidLoad() {
        super.viewDidLoad()
        
        
    }


}

